// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgres

import (
	"time"
)

type Chat struct {
	ID        int64
	Room      string
	Author    string
	Message   string
	CreatedAt time.Time
}

type Chatter struct {
	Username  string
	Password  string
	Email     string
	CreatedAt time.Time
}

type Room struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}
